name: methane-cv
channels:
  - conda-forge
  - microsoft
  - pytorch
  - nvidia
  - nodefaults  # https://docs.conda.io/projects/conda/en/4.6.1/user-guide/tasks/manage-environments.html
dependencies:
  - adlfs==2024.12.0
  - appdirs==1.4.4
  - boto3==1.36.3
  - botocore==1.36.3
  - cloudpickle==3.0.0
  - conda-forge::azure-ai-ml==1.23.1
  - conda-forge::azure-core==1.32.0
  - conda-forge::azure-keyvault-secrets==4.8.0
  - conda-forge::fastai==2.7.19  # requirement of omnicloudmask
  - conda-forge::fsspec==2024.12.0  # for azureml-fsspec
  - conda-forge::gdown==5.2.0  # requirement of omnicloudmask
  - conda-forge::multimethod==2.0  # for earthaccess
  - conda-forge::pqdm==0.2.0  # for earthaccess
  - conda-forge::pydantic==2.10.6
  - conda-forge::python-cmr==0.13.0  # for earthaccess
  - conda-forge::s3fs==2024.12.0  # for earthaccess
  - conda-forge::tinynetrc==1.3.1  # for earthaccess
  - cryptography==44.0.0
  - dask==2025.1.0
  - gdal==3.9.0
  - geojson-pydantic==1.0.1
  - geojson==3.2.0
  - geopandas==1.0.1
  - gitpython==3.1.44
  - google-cloud-storage==3.0.0
  - h5netcdf==1.5.0
  - ipykernel==6.29.5
  - ipython==8.31.0
  - ipywidgets==8.1.6
  - marshmallow==3.26.0
  - matplotlib==3.9.1
  - mlflow==2.20.0
  - mypy-boto3-s3==1.36.0
  - mypy==1.14.1
  - nbstripout==0.8.1
  - numpy==1.26.4
  - ocl-icd-system==1.0.0
  - omegaconf==2.3.0
  - opencv==4.10.0  # =headless_py310h1766cdc_15  # headless has fewer dependencies
  - pandas==2.2.3
  - pip==25.0
  - planetary-computer==1.0.0
  - pooch==1.8.2
  - pyarrow==16.1.0
  - pydantic-settings==2.3.4
  - pystac-client==0.8.5
  - pystac==1.12.1
  - pytest-benchmark==5.1.0
  - pytest-dependency==0.5.1
  - pytest==8.3.4
  - python=3.10.12
  - pytorch-lightning==2.1.3
  - pytorch::pytorch==2.4.0
  - pytorch::torchdata==0.7.1
  - pytorch::torchvision==0.19.0
  - rasterio==1.3.10
  - requests==2.32.3
  - rioxarray==0.18.2
  - ruff==0.3.7
  - scikit-image==0.25.1
  - segmentation-models-pytorch==0.4.0
  - structlog==24.1.0
  - tenacity==9.0.0
  - tensorboard==2.18.0
  - torchgeo==0.5.2
  - types-requests==2.32.0.20241016
  - utm==0.7.0
  - xarray-einstats==0.8.0
  - xarray==2025.1.1
